### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [pks/zipf#1]
Dear @zipf,

I've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository. You may want to spread a word on Twitter or on other media :)

Thank you for the project!

**Comment by zipf** [comment]
Dear Andrei,

On Sun, Apr 16, 2017 at 8:13 PM, Andrei Beliankou <notifications@github.com>
wrote:

> Dear @zipf <https://github.com/zipf>,
>
> I've recently added your project to our RubyNLP list:
> https://github.com/arbox/nlp-with-ruby
>
> I wonder if you want to participate in the Ruby for NLP network. You could
> do this in a very simple step by adding the rubynlp topic to your GitHub
> repository. You may want to spread a word on Twitter or on other media :)
>
> Thank you for the project!
>

Not sure what project you refer to, as I usually program in Perl and R.
Anyway, I loved your RubyNLP initiative. We should have something like that
in Perl. I may even try to do it.

Kind regards,
Enrique

**Comment by arbox** [comment]
Dear @pks , dear @zipf ,
thank you for your responses. Please use the list if you find it useful! Please spread the word if you may want to :)
